// Kafka Server JAAS 配置文件

// KafkaServer 用于客户端到 Kafka 的认证
KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_alice="alice-secret"
    user_bob="bob-secret";
};

// Client 用于 Kafka 连接 Zookeeper
Client {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    username="kafka"
    password="kafka-secret";
};
