// Zookeeper JAAS 配置文件

// Server 用于 Zookeeper 自己的认证
Server {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    user_kafka="kafka-secret";
};

// Client 用于 Zookeeper 客户端（如 Kafka）
Client {
    org.apache.zookeeper.server.auth.DigestLoginModule required
    username="kafka"
    password="kafka-secret";
};
